openapi: 3.0.0
info:
  version: 1.0.0
  title: Athenix API
servers:
  - url: 'https://athenix.bcserver.xyz'
    description: Athenix dev api
  - url: 'https://api.athenix.ai'
    description: Athenix Prod api
paths:
  '/v1/platform/{platformName}/shop/{platformShopId}/recommend/{recommenderType}/fine-tuning':
    post:
      tags:
        - partner
      summary: Fine tuning active ai products recommend
      parameters:
        - name: platformName
          in: path
          required: true
          description: platform name
          schema:
            type: string
            enum:
              - shopify
            example: shopify
        - name: platformShopId
          in: path
          required: true
          description: platform shop id
          schema:
            type: string
            example: '12345678'
        - name: recommenderType
          in: path
          required: true
          description: recommendation type
          schema:
            type: string
            enum:
              - fbt
            example: fbt
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - originalProduct
              properties:
                excludeProducts:
                  type: array
                  description: exclude product ids
                  items:
                    $ref: '#/components/schemas/Product'
                originalProduct:
                  type: object
                  required:
                    - type
                  properties:
                    type:
                      type: string
                      enum:
                        - all
                        - collections
                        - tags
                        - specific
                    items:
                      oneOf:
                        - type: array
                          items:
                            type: string
                        - type: string
            examples:
              Register with all products:
                value:
                  excludeProducts:
                    - id: '35123512352'
                      variant: all
                      totalVariant: 0
                    - id: '35123512352'
                      variant:
                        - '35235235'
                        - '352352'
                      totalVariant: 3
                  originalProduct:
                    type: all
                    items: []
              Register with collections:
                value:
                  originalProduct:
                    type: collections
                    items:
                      - '23512351235125'
                      - '84512351235235'
              Register with products tags:
                value:
                  originalProduct:
                    type: tags
                    items:
                      - adidas
                      - autumn
                      - summer
              Register with specific products:
                value:
                  originalProduct:
                    type: specific
                    items:
                      - id: '35123512352'
                        variant: all
                        totalVariant: 5
                      - id: '35123512323'
                        variant:
                          - '35235235'
                          - '352352'
                        totalVariant: 3
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
              examples:
                Active fine tuning succesfully!:
                  value:
                    data:
                      msg: Active fine tuning fbt recommend successfully
                    error: 'null'
                    code: 200
                No configuration change!:
                  value:
                    data:
                      msg: 'No configuration change, skip active fine tuning fbt recommend'
                    error: 'null'
                    code: 200
        '401':
          description: Unauthentiation response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                Token missing:
                  value:
                    data: 'null'
                    error:
                      message: API_TOKEN is missing
                      code: INVALID_TOKEN
                Invalid token:
                  value:
                    data: 'null'
                    error:
                      message: API_TOKEN is invalid
                      code: INVALID_TOKEN
        '404':
          description: Not found response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                Shop not found:
                  value:
                    data: 'null'
                    error:
                      message: shop not found
                      code: NOT_FOUND
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - API_TOKEN: []
      servers:
        - url: 'https://athenix.bcserver.xyz'
          description: Athenix dev api
        - url: 'https://api.athenix.ai'
          description: Athenix Prod api
components:
  securitySchemes:
    API_TOKEN:
      type: apiKey
      name: API_TOKEN
      in: header
  schemas:
    SuccessResponse:
      type: object
      properties:
        data:
          type: object
          properties:
            msg:
              type: string
              example: successfully
        error:
          type: string
          example: 'null'
        code:
          type: number
          enum:
            - 200
          example: 200
    ErrorResponse:
      type: object
      properties:
        data:
          oneOf:
            - type: string
              example: 'null'
            - type: object
        error:
          type: object
          properties:
            message:
              type: string
              example: API_TOKEN is missing
            code:
              type: string
              enum:
                - INVALID_TOKEN
                - NOT_FOUND
              example: INVALID_TOKEN
    Product:
      type: object
      title: Product
      properties:
        id:
          type: string
          example: '35123512352'
        variant:
          oneOf:
            - type: array
              items:
                type: string
            - type: string
        totalVariant:
          type: number
      required:
        - id
        - variant
        - totalVariant
      x-examples:
        Product with all variants:
          id: '35123512352'
          variant: all
          totalVariant: 0
        'Product with specific variants ':
          id: '35123512352'
          variant:
            - '23523523523'
            - '32523523223'
          totalVariant: 3
